#!/bin/sh

_set_prompt() {
  local txtblk='\[\e[0;30m\]' # Black - Regular
  local txtred='\[\e[0;31m\]' # Red
  local txtgrn='\[\e[0;32m\]' # Green
  local txtylw='\[\e[0;33m\]' # Yellow
  local txtblu='\[\e[0;34m\]' # Blue
  local txtpur='\[\e[0;35m\]' # Purple
  local txtcyn='\[\e[0;36m\]' # Cyan
  local txtwht='\[\e[0;37m\]' # White
  local bldblk='\[\e[1;30m\]' # Black - Bold
  local bldred='\[\e[1;31m\]' # Red
  local bldgrn='\[\e[1;32m\]' # Green
  local bldylw='\[\e[1;33m\]' # Yellow
  local bldblu='\[\e[1;34m\]' # Blue
  local bldpur='\[\e[1;35m\]' # Purple
  local bldcyn='\[\e[1;36m\]' # Cyan
  local bldwht='\[\e[1;37m\]' # White
  local unkblk='\[\e[4;30m\]' # Black - Underline
  local undred='\[\e[4;31m\]' # Red
  local undgrn='\[\e[4;32m\]' # Green
  local undylw='\[\e[4;33m\]' # Yellow
  local undblu='\[\e[4;34m\]' # Blue
  local undpur='\[\e[4;35m\]' # Purple
  local undcyn='\[\e[4;36m\]' # Cyan
  local undwht='\[\e[4;37m\]' # White
  local bakblk='\[\e[40m\]'   # Black - Background
  local bakred='\[\e[41m\]'   # Red
  local bakgrn='\[\e[42m\]'   # Green
  local bakylw='\[\e[43m\]'   # Yellow
  local bakblu='\[\e[44m\]'   # Blue
  local bakpur='\[\e[45m\]'   # Purple
  local bakcyn='\[\e[46m\]'   # Cyan
  local bakwht='\[\e[47m\]'   # White
  local txtrst='\[\e[0m\]'    # Text Reset

  : ${GIT_BASH_COMPLETION:=/etc/bash_completion.d/git-prompt}
  if [ -z "$(type -t __git_ps1)" ]; then
    if [ ! -e "${GIT_BASH_COMPLETION}" ]; then
      return
    fi
    . $GIT_BASH_COMPLETION
  fi

  export GIT_PS1_SHOWDIRTYSTATE=true
  export GIT_PS1_SHOWCOLORHINTS=true
  export GIT_PS1_UNTRACKEDFILES=true
  export PROMPT_COMMAND="__git_ps1 '${txtblu}\u@\h${txtrst}:\w${txtrst}'  '\\$ '"
}

_set_prompt
unset -f _set_prompt
